### ISSUE TITLE
Bot não carrega playlist.

### ISSUE THREAD

**Issue by vSilva-gb** [HellpMe/Project-Columbine#10]
O bot não carrega playlist, apenas mix do youtube, seria um bug, ou eu que configurei algo errado?

**Comment by vSilva-gb** [comment]
Na verdade, parece que ele tem um "limite" de musicas por playlist

**Comment by vSilva-gb** [comment]
Na verdade, se na playlist tiver algum vídeo que tenha sido excluido, ele automaticamente não carrega, teria como resolver?

**Comment by HellpMe** [comment]
@vSilva-gb, poderia enviar uma print/screenshot do erro ?

**Comment by vSilva-gb** [comment]
![image](https://user-images.githubusercontent.com/41455280/116594588-c5dec980-a8f8-11eb-99ca-b1b2cc68dc99.png)

E a playlist que estou tentando tocar é essa: https://www.youtube.com/playlist?list=PLi8lJIpSWZEujlrMEODuCemBK9OOTCBxV

**Comment by HellpMe** [comment]
Consegue confirmar para mim se a playlist está publica ?

**Comment by HellpMe** [comment]
> Consegue confirmar para mim se a playlist está publica ?

O erro é que a playlist está em modo "privada" todo player só consegue ler as playlist publicas.

**Comment by vSilva-gb** [comment]
Está não listada, porem outras playlists publicas estão com o mesmo problema, um exemplo seria essa
https://www.youtube.com/playlist?list=PLi8lJIpSWZEslj0A87XsFXOaUyz7JgfjK

**Comment by HellpMe** [comment]
Estranho, ele não está conseguindo "ler" a playlist

**Comment by vSilva-gb** [comment]
Sim, pensei que tinha algo a ver com músicas “excluídas” que continham nas playlist, porém essa última que apaguei não tem nenhum vídeo excluído e ainda apresenta erros

**Comment by HellpMe** [comment]
Adicionando musica por musica funciona corretamente, aparentemente o problema tá na playlist..

**Comment by vSilva-gb** [comment]
Sim, mais que problema teria sendo que  a única configuração que pode ser feita em uma playlist é ser “privada, não listada é pública” é essa está pública

**Comment by HellpMe** [comment]
Irei procurar atualizar/rever o código para ver o porque disso estar acontecendo.

**Comment by HellpMe** [comment]
@vSilva-gb, achei o problema, é a versão do lavalink ela não está conseguindo carregar as musicas, porem se você atualizar para a versão atual não irá ter suporte para os filtros.

**Comment by HellpMe** [comment]
@vSilva-gb, arrumei esse problema, irei upar a nova versão agora.
