### ISSUE TITLE
Após adicionar uma musica a fila, era para de reproduzir

### ISSUE THREAD

**Issue by vSilva-gb** [HellpMe/Project-Columbine#19]
Bom, tá com um bug, que testei no sistema linux, que funciona da seguinte forma, quando você coloca uma musica na fila, enquanto já tem uma tocando, a musica atual para de tocar, daí toca apenas a próxima da fila, tem alguma ideia do que seja?

**Comment by HellpMe** [comment]
Para eu verificar esse erro preciso das seguintes informações,
versão do lavalink, onde você ta hospedando e oque aparece no console quando você adiciona as musica.

**Comment by vSilva-gb** [comment]
Então, versão do Lavalink que estou usando é a seguinte.
https://ci.fredboat.com/repository/download/Lavalink_Build/8845:id/Lavalink.jar?guest=1

E estou hospedando na Discloud e não dá nenhum erro no console, porem não verifiquei a log do lavalink
E vou tentar verificar qual linux que estão usando.

**Comment by HellpMe** [comment]
Os teste que eu fiz usando o servidor lavalink em localhost não apresentou esses erros, ele apenas deu uma "leve" travadinha e continuou reproduzindo a musica.
Provavelmente seja o servidor lavalink que você está usando que está demorando pra atualizar a lista de musicas e pulando de faixas, tente executa-lo em localhost se o erro persistir entre em contato comigo novamente.
Pouco provável que seja erro no código, porem não posso upar uma nova atualização agora pois estou criando a dashboard do bot e por enquanto até que eu não há termine não irei deixar publica.
